name: grocery_dbt
version: '1.0'
config-version: 2
profile: grocery_gcp
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
