services:
  airflow-webserver:
    pull_policy: never
    build:
      context: ./airflow
      dockerfile: Dockerfile

  airflow-scheduler:
    pull_policy: never
    build:
      context: ./airflow
      dockerfile: Dockerfile

  airflow-worker:
    pull_policy: never
    build:
      context: ./airflow
      dockerfile: Dockerfile

  airflow-dag-processor:
    pull_policy: never
    build:
      context: ./airflow
      dockerfile: Dockerfile
